spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  security:
    basic:
      enabled: false

  application:
    name: payment-service

logging:
  level:
    web: debug

server:
  port: 8083

eureka:
  client:
    service-url:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: http://localhost:8761/eureka
    prefer-ip-address: true

biapay:
  base-url: https://api-dev.biapay.net/gateway





